name: Handlebars-helpers CI

on: 
  # Trigger the workflow on push or pull request,
  # but only for the master branch (or main)
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  release:
    types: 
      - created
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30   # Just in case something goes realy real realy BAD.....

    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [10.x, 12.x, 14.x, 16.x]
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - name: Checkout GITHub code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile   # will run `yarn install --frozen-lockfile` command

      - name: Lint code
        run: yarn lint

      - name: Run tests against code
        run: yarn test
        env:
          CI: true
          name: Handlebars-helpers CI

      - name: Publish to NPM only on a relase event
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
